Add support for disabling use of routing entirely at the compiler level
VROOM-Project/vroom pull request #676
Opened 2022-02-18 18:42 UTC by aardvarkk

- Allows the compile to take place without ASIO
- Optimization still works if using a custom cost matrix
- Default compilation behaviour should be identical to previous
- To compile, just run `USE_ROUTING=false make`

## Issue

https://github.com/VROOM-Project/vroom/issues/675

2022-02-22 16:01 UTC, jcoupey commented
Thanks for submitting this idea and a PR. It makes perfect sense to have an easy way to drop unused stuff when only using custom matrices.

2022-02-22 16:39 UTC, jcoupey requested changes
I think this is fine as soon as we have a proper handling of input with missing custom matrices.

Please also add a changelog entry and [run `clang-format`](https://github.com/VROOM-Project/vroom/blob/master/CONTRIBUTING.md#automatic-formatting).

2022-02-22 16:39 UTC, jcoupey commented on src/structures/vroom/input/input.cpp
>  void Input::add_routing_wrapper(const std::string& profile) {
The `add_routing_wrapper` definition should also be conditioned by `USE_ROUTING`.

2022-02-22 16:39 UTC, jcoupey commented on src/structures/vroom/input/input.cpp
> +    #if USE_ROUTING
A plain removal of this portion is a bit extreme. As a result, we hit the assert on line 667 when running on a "usual" problem with no custom matrix:

```
vroom -i docs/example_1.json
vroom: structures/vroom/input/input.cpp:677: vroom::Input::set_matrices(unsigned int)::<lambda(const std::vector<std::__cxx11::basic_string<char> >&)>: Assertion `d_m != _durations_matrices.end()' failed.
Aborted (core dumped)
```

The expected behavior here would be to get a nice and explicit error. Maybe we could keep `add_routing_wrapper` after all but simply have it throw with "VROOM compiled without routing support" a bit like here:

https://github.com/VROOM-Project/vroom/blob/e3938092e60e1b2d2c5da58feef0b5fe819cd5f4/src/structures/vroom/input/input.cpp#L88

2022-02-22 16:45 UTC, jcoupey commented on src/makefile
>  # Checking for libosrm
Update: checking whether `libosrm` is installed should only happen with `USE_ROUTING=true`. Disabling routing will remove the libosrm includes anyway so we'd then be linking a lot of unnecessary stuff.

2022-02-22 17:48 UTC, aardvarkk commented
@jcoupey Thanks for the feedback. I believe I have incorporated all of the requested changes. Please let me know if you feel I've missed anything.

2022-02-23 10:57 UTC, jcoupey commented
Thanks for the changes, the diff is actually much simpler now. I'll simply remove modification for older changelog entries (probably automatic IDE formatting) before merging.

2022-02-23 10:57 UTC, merged

2022-03-18 13:37 UTC, jcoupey commented
Except for the entry on PDPTW, [unreleased stuff](https://github.com/VROOM-Project/vroom/blob/master/CHANGELOG.md#unreleased) is pretty much technical but not directly related to solving. The next release will probably wait for more solving-related stuff to be included in `master`.