Fix/issue#683
VROOM-Project/vroom pull request #698
Opened 2022-04-21 19:18 UTC by PattyDePuh

## Issue [#683](https://github.com/VROOM-Project/vroom/issues/683)

Created an accessor for the `has_custom_location_index` variable inside `Input`.
Accessor is used at the end of `parse()`, if no custom matrizes where found inside JSON input.

2022-04-25 07:24 UTC, jcoupey requested changes
Thanks for submitting a PR!

The changes you made would work when parsing a json problem with `location_index` values and no matrix but it would still be possible to have inconsistent definitions when using the C++ API.
This is pretty much the same as in #628: we should enforce the checks at a lower level in the `Input` class so that they apply both to json-defined problems and uses of the C++ API.

A good place to do this is at the beginning of [`Input::set_matrices`](https://github.com/VROOM-Project/vroom/blob/39438be9e5b61d88a5608a71b369994fc212f49a/src/structures/vroom/input/input.cpp#L634) because this function is called after the problem definition, prior to solving. There is already a check for missing location index there.

2022-04-26 08:47 UTC, PattyDePuh commented
Thanks for Feedback.

2022-04-27 07:59 UTC, jcoupey reviewed
Thanks for the changes, the check in `Input::set_matrices` does the job! Can you please add a changelog entry under the unreleased/fixed section?

2022-04-27 07:59 UTC, jcoupey commented on src/utils/input_parser.cpp
> +  } else {
Not really a fan of a logic branch that does nothing, and I don't think we really need to comment here on stuff that other parts of the code is responsible for. We can probably revert all changes to `input_parser.cpp`?

2022-04-27 10:34 UTC, PattyDePuh commented
Everything is cleaned up and ready to merge.

2022-04-27 11:11 UTC, jcoupey approved these changes

2022-04-27 11:14 UTC, merged